### ISSUE TITLE
запускаю release.exe и ничо не происходит

### ISSUE THREAD

**Issue by dx9scope** [insage1337/cs2_external_internal#10]
Текст

**Comment by dx9scope** [comment]
винда 11

**Comment by dx9scope** [comment]
попробовал скомпилить и охуел мужик это что блять такое
![image](https://github.com/insage1337/cs2_external_internal/assets/131756274/7e37eaee-e0da-4f1c-b8de-61271e354d1d)

**Comment by insage1337** [comment]
в релизе майнер, код поправил, с инклюдами сам думаю разберешься

**Comment by dx9scope** [comment]
> в релизе майнер, код поправил, с инклюдами сам думаю разберешься

УРА

**Comment by insage1337** [comment]
ладно если без рофла там анти отладка, и лоадер не запускается если какие-то файлы и процессы запущены

**Comment by insage1337** [comment]
5.166.86.24 - - [17/Feb/2024:16:37:41 +0300] "GET /panel/03d35-944c1-3d8d6-12302 HTTP/1.0" 302 280 "-" "Debug-reversing" если это ты то так и есть
