### ISSUE TITLE
Aimbot works not good

### ISSUE THREAD

**Issue by Cyk-Fad** [insage1337/cs2_external_internal#7]
When i enable aimbot,fov circle and aimbot itself dosen't work.But when i hide the window and switch the window(cs2 and notepad) then it start working.I checked out the code but i can't find the problem is

**Comment by insage1337** [comment]
try to enable rcs and set rcs fov. are you using perfect world cs?

**Comment by Cyk-Fad** [comment]
> try to enable rcs and set rcs fov. are you using perfect world cs?

okay problem solved now.I suggest enable aimbot and rcs in config(in code)

**Comment by Cyk-Fad** [comment]
> try to enable rcs and set rcs fov. are you using perfect world cs?

do u have discord or other contacts?If u'd like to, i would make the cheat with u,thanks a lot.I'm chinese

**Comment by Cyk-Fad** [comment]
> i don't want to develope something, but, if you have a question my discord id is 302878998516465665

how to add u with discord id?I don't know bro.

**Comment by Cyk-Fad** [comment]
> i don't want to develope something, but, if you have a question my discord id is 302878998516465665

my discord is Ap15#2025
