### ISSUE TITLE
trouble for build the release

### ISSUE THREAD

**Issue by geskard** [insage1337/cs2_external_internal#8]
i'm not quite understand about "Include" to Project. I put the Include folder into the project folder, but i failed when i attempt to release x64 build like this

![Screenshot 2024-02-16 110959](https://github.com/insage1337/cs2_external_internal/assets/134226529/1b1583fe-16eb-4cfc-bc82-30f0ebf0983a)

**Comment by insage1337** [comment]
https://codeyarns.com/tech/2013-09-22-how-to-add-include-directory-in-eclipse-cdt.html#gsc.tab=0

include to project cs2_external_internal-main\evo\utils\SDL3\include
include to project cs2_external_internal-main\evo\utils\SDL3\lib

**Comment by insage1337** [comment]
removed useless sdl for you, hopefully now you can compile it
